apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    rc: nginx-test
  name: nginx-test
spec:
  replicas: 2
  selector:
    app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-svc
        image: nginx
        ports:
        - containerPort: 80
